services:
  - type: web
    name: life-os-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATA_FILE
        value: ./data/life-os.json
      - key: CORS_ORIGIN
        value: "*"
      - key: TIMEZONE
        value: Africa/Nairobi
      - key: DATABASE_URL
        sync: false   # set this in Render dashboard -> Environment, paste your Neon connection string
      - key: DATABASE_URL_SYNC
        fromService:
          type: pserv
          name: life-os-db
          property: connectionString
